instagram_web/blueprints/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from models.user import User
from models.user_images import Image
from werkzeug.security import generate_password_hash, check_password_hash
import re
import datetime
from flask_login import current_user, login_user, login_required
from werkzeug.utils import secure_filename
from helpers import upload_file_to_s3
from config import S3_BUCKET, S3_LOCATION


users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')


@users_blueprint.route('/create', methods=['POST'])
def create():
    em = request.form.get('email')
    us = request.form.get('username')
    pa = request.form.get('password')

    if len(pa) > 6:
        if re.search(r'[A-Z]', pa) and re.search(r'[a-z]', pa) and re.search(r'\W', pa):
            hashed_pa = generate_password_hash(pa)
            new_user = User(email=em, username=us, password=hashed_pa)

            if new_user.save():
                login_user(new_user)
                return redirect(url_for('users.index'))
            else:
                return render_template('users/new.html', errors=new_user.errors)
        else:
            return render_template('users/new.html', errors='The password requires uppercase, lowercase and at least one special character')

    else:
        return render_template('users/new.html', errors='That password is too short!')


@users_blueprint.route('/<username>', methods=["GET"])
def show(username):
    user = User.get(User.username == username)
    image_list = Image.select().where(
        Image.user_id == user.id)
    return render_template("users/profile.html", username=username, user=user, image_list=image_list)


@users_blueprint.route('/', methods=["GET"])
def index():
    if current_user.is_authenticated:
        images = Image.select(Image, User).join(
            User).where(Image.user_id != current_user.id).order_by(Image.created_at.desc())
        return render_template('users/index.html', images=images)
    else:
        images = Image.select().order_by(Image.created_at.desc())
        return render_template('users/index.html', images=images)


@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    if id == str(current_user.id):
        return render_template('users/edit.html')
    else:
        flash('Unauthorized request.', 'danger')
        return redirect(url_for('users.index'))


@users_blueprint.route('/<id>/update', methods=['POST'])
def update(id):
    email = request.form.get('email')
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.get_by_id(id)
    user.email = email
    user.username = username
    if len(password) > 0:
        if len(password) > 6:
            if re.search(r'[A-Z]', password) and re.search(r'[a-z]', password) and re.search(r'\W', password):
                hashed_pass = generate_password_hash(password)
                user.password = hashed_pass
            else:
                return render_template('users/edit.html', errors='The password requires uppercase, lowercase and at least one special character')
        else:
            return render_template('users/edit.html', errors='That password is too short!')

    if user.save():
        flash(u'Updated successfully!', 'success')
        return redirect(url_for('users.edit', id=current_user.id))

    else:
        flash('failwhale')
        return render_template('users/edit.html')


@users_blueprint.route('/<id>/upload', methods=['POST'])
def upload(id):
    if "user_file" not in request.files:
        flash("No file was chosen! :O")
        return redirect(url_for('users.edit', id=id))
    file = request.files.get('user_file')
    file_name = secure_filename(file.filename)
    if file_name != '':
        user = User.get_by_id(current_user.id)
        error = str(upload_file_to_s3(file, S3_BUCKET))

        user.image = S3_LOCATION + file_name
        if user.save():
            return redirect(url_for('users.edit', id=id))
        else:
            return render_template('users/index.html', error=error)
    else:
        flash('File has no name!')
        return redirect(url_for('users.edit'))


@users_blueprint.route('/search', methods=['POST'])
def search():
    search_input = request.form.get("search")
    text = re.sub(r'\s', '', search_input)
    text_lower = text.lower()
    search_list = list(text_lower)
    users = User.select()
    user_list = []
    for user in users:
        i = 0
        username = re.sub(r'\s', '', user.username)
        username_lower = username.lower()
        for char in search_list:
            if username_lower.find(char) >= 0:
                username_lower.replace(char, '', 1)
                i += 1

        if i == len(search_list):
            user_list.append(user)

    return render_template('users/search.html', text=search_list, user_list=user_list)

instagram_web/blueprints/users/templates/users/donate.html
{% extends "_layout.html" %}

{% block header %}
<meta charset="utf-8">
<script src="https://js.braintreegateway.com/web/dropin/1.18.0/js/dropin.min.js"></script>
{% endblock %}

{% block content %}
 <!-- {{client_token}} -->
 <form action="{{url_for('checkout')}}" method="POST" id="donation_form">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

  <input type="number" name="amount" value=""/>

  <input type="hidden" id="nonce" name="payment_method_nonce">

</form> 


<div id="dropin-container"></div>
<button id="submit-button" form="donation_form" type="submit">Request payment method</button>
 
<script>
  var form = document.querySelector('#donation_form');
  var button = document.querySelector('#submit-button');

  braintree.dropin.create({
    authorization: '{{client_token}}',
    container: '#dropin-container'
  }, 
  
  function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }
        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
      });
    });

</script>

{% endblock %}

instagram_web/blueprints/users/templates/users/index.html
{% extends "_layout.html" %}

{% block title %}
Homepage
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        {% for image in images%}
        <div class="col-lg-4 col-sm-5">
            <div class="card" id='{{image.id}}' style="width: 100%;">
                <img class='card-img-top' id='img{{image.id}}' src={{image.source}} width='100%'>
                <div class="caption-index">
                    {% if image.caption == None %}
                    #NoCaptionIsSexy
                    {% else %}
                    {{image.caption}}
                    {% endif %}
                </div>
                <div class="card-body d-flex justify-content-around align-items-center">
                    <h3 class='card-text'>
                        <a href="{{url_for('users.show', username = image.user.username)}}">
                            {{image.user.username}}
                        </a>
                    </h3>
                    <a class='dollar-box d-flex justify-content-center align-items-center'
                        href="{{url_for('donations.new', image_id=image.id)}}">
                        <i class="fas fa-dollar-sign"></i>
                    </a>
                </div>
            </div>

            <div class="modal fade" id="picModal{{image.id}}" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-scrollable" role="document">
                    <div class="modal-content">
                        <div class="modal-header"><a href="{{url_for('users.show', username = image.user.username)}}">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">{{image.user.username}}
                                </h5>
                            </a>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <img width='300px' src="{{image.source}}" alt="">
                            <div>
                                {{image.caption}}
                            </div>
                            <a href="{{url_for('donations.new', image_id=image.id)}}"><i
                                    class="fas fa-dollar-sign"></i></a>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary">Das enough.</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-lg-2 col-1"></div>
        {% endfor %}
    </div class="row">
</div>


<script>
    $(document).ready(() => {
        // $('.card').click((e) => {
        //     id = e.currentTarget.id
        //     $(`#picModal${id}`).modal('toggle')
        // })
    })

</script>
{% endblock %}

instagram_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<form action='{{url_for("users.create")}}' method='POST'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input name='email' type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputU">Username</label>
        <input name='username' type="text" class="form-control" id="exampleInputU">
    </div>
    <div class="form-group">
        <label for="passInput">Password</label>
        <input name='password' type="password" class="form-control" id="passInput">
        <div id='passReply'></div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% for error in errors %}
{{error}}
{% endfor %}
{% endblock %}

instagram_web/blueprints/users/templates/users/profile_photo.html
{% extends "_layout.html" %}

{% block title %}
  Upload Profile Photo
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<form action="{{url_for('users.upload_file_to_s3',id=current_user.id)}}" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
    <input type="file" name="profile_photo">
    <input type="submit" value="Submit">
</form>


<img src="{{image}}" alt="{{image}}" width="50%">

{% endblock %}

instagram_web/blueprints/users/templates/users/profilepage.html
{% extends '_layout.html' %}
{%block content%}
<!-- <div style="display: flex; flex-direction: column"> -->
<!-- <div style="box-sizing: border-box;"> -->
<!-- <div style="display: flex; flex-direction: row;"> -->
<!-- Modal -->
<div class="modal fade" id="plusModal" tabindex="-1" role="dialog" aria-labelledby="plusModalLongTitle"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="background-color:rgb(52, 50, 50); color:lightpink">
      <div class=" modal-header" style="background-color:rgb(52, 50, 50);">
        <h5 class=" modal-title" id="exampleModalLabel">Select a profile image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color:lightpink">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="display: flex; justify-content: center;">

        <form action="{{url_for('users.upload')}}" method="POST" enctype="multipart/form-data">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"></input>

          <input type="file" name="user_file" class="profileinput" id="profileinput" accept="image/*"
            onchange=previewImage(event) />

          <div class="profilelabel-div">
            <label style="width:200px; height:12px; border-radius:9%" class="profilelabel" for="profileinput">Choose
              Image</label>
          </div>
          <br>
          <button class="upload-profile" type="submit">Upload</button>
        </form>
      </div>
      <!-- <div style="display:flex;flex-direction:column"> -->
      <h6 style="display: flex; justify-content: center;">Preview:</h6>
      <div
        style="border:lightpink solid 2px; width:200px; height:200px; margin:0 auto; display: flex; justify-content:center; align-items: center; border-radius:50%;">
        <img style="width: 190px; height:190px; object-fit: cover; border-radius: 50%;display:none;" id="your-image" />
      </div>
      <h6 style="display: flex; justify-content: center; padding-top:20px;">Current Image:</h6>
      <div style="padding-bottom:20px;">
        <div
          style="display: flex; justify-content: center; align-items:center; border: 2px solid lightpink; width:200px; height:200px; border-radius:50%; margin: 0 auto;">
          <img style="width: 190px; height:190px; object-fit: cover; border-radius: 50%;;"
            src=" https://jynmunbucket.s3-ap-southeast-1.amazonaws.com/{{user.profile_image}}" />
        </div>
      </div>
      <!-- </div> -->
    </div>
  </div>
</div>
<div style="display: flex; flex-direction: row; margin-top: 5vh">
  <div style="display: flex; flex-direction: row;">
    <div style="border-radius:50%; width: 190px; height: 190px; margin-left:220px; position: relative;">
      <img class="img-thumbnail rounded-circle"
        style="width: 190px; height:190px; object-fit: cover; border-radius: 50%;border: 2px solid white;"
        src="https://jynmunbucket.s3-ap-southeast-1.amazonaws.com/{{user.profile_image}}" />
      <button style="position: absolute; bottom: 10px; right: 20px; width: 30px; height: 30px;" type="button"
        class="rounded-circle" id="plus-modal" data-toggle="modal" data-target="#plusModal">
        +
      </button>
    </div>
  </div>
  <div style="margin-left: 3em; display: flex; flex-direction: column; justify-content:center; align-items: center;">
    {% if not user.id==current_user.id %}
    <h1 style="font-weight: bold">{{user.username}}</h1>
    {% if not current_user.is_following(user) %}
    <a href="{{url_for('follower_following.create', idol_id=user.id)}}" class="btn btn-primary" style="width:100px"
      action="POST">Follow</a>
    {% else %}
    <a href="{{url_for('follower_following.delete', idol_id=user.id)}}" class="btn btn-primary" style="width:100px"
      action="POST">Unfollow</a>
    {% endif %}
    {% else %}
    <h1 style="font-weight: bold">{{user.username}}</h1>
    <p> {{user.username}}</p>
    {% endif %}
  </div>
  <div style="display: flex; align-items: center; width:300px; justify-content: space-between; margin-left: 100px;">
    <div style="display: flex; flex-direction: column; justify-content:center; align-items: center;">
      <div>
        <h1>{{user.id}}</h1>
      </div>
      <div>
        <h6>Posts</h6>
      </div>
    </div>
    <div style="display: flex; flex-direction: column; justify-content:center; align-items: center;">
      <div>
        <h1>{{user.following | length}}</h1>
      </div>
      <div>
        <h6>Followers</h6>
      </div>
    </div>
    <div style="display: flex; flex-direction: column; justify-content:center; align-items: center;">
      <div>
        <h1>{{user.followers | length}}</h1>
      </div>
      <div>
        <h6>Following</h6>
      </div>
    </div>
  </div>
</div>

<div style="display: flex; justify-content: center; margin-top: 30px;">
  <a href="{{url_for('users.show',username=user.username)}}" id="edit-details" class="btn btn-link"
    style="color:rgb(245, 150, 180); text-decoration:none;border: 2px solid rgb(245, 116, 180); width: 950px; display: flex; justify-content: center;">Edit
    Details</a>
</div>

<div class="row d-flex flex-column" style="margin-top: 50px; margin-left: 165px">
  <div class="col-lg-5">
    <form action="{{url_for('users.upload')}}" method="POST" enctype="multipart/form-data">
      <div class="rounded-circle"
        style="background: linear-gradient(to right, red, orange,red, purple); margin-left:100px;width: 100px; height: 100px ">
        <div class="rounded-circle" id="plus-highlight"
          style="border-radius:50%; border: 1px solid pink; width: 100px; height: 100px; display: flex; justify-content: center; align-items: center;">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"></input>
          <input type="file" name="user_file" id="plusfile" class="plusfile" />
          <label style="font-weight:300;" for="plusfile">+</label>
        </div>
      </div>
    </form>
  </div>

  <div class="col-lg-5">
    <h6 style="font-weight:100; margin-left:132px; margin-top: 10px">New</h6>
  </div>

  <div
    style="display: flex;padding-left: 160px; flex-wrap:wrap; justify-content:start; flex-direction:row; margin-left:-100px;">
    {% for image in image_list %}
    <div
      style="background-color:white;width:300px; height:300px; display: flex; object-fit: cover; justify-content:center; margin-right:1cm; margin-top:1cm">
      <img style="max-height:300px; max-width: 300px; object-fit: cover;" src={{image.user_image}} />
    </div>
    {% endfor %}
    <div class="add-image-div"
      style=" width:300px; height:300px; margin-top:1cm; display:flex; justify-content:center; align-items: center;">
      <button type="button" class="btn btn-link" id="add-image" data-toggle="modal" data-target="#exampleModal">
        +
      </button>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content"
            style="background-color:rgb(52, 50, 50); color:lightpink; margin-left:30px; margin-right:30px">
            <div class="modal-header" style="background-color:rgb(52, 50, 50); color:lightpink">
              <h5 class="modal-title" id="exampleModalLabel">Add Picture</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"
                style="color:rgb(252, 117, 137)">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form action="{{url_for('images.upload_image')}}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"></input>


                <div
                  style="border:lightpink solid 2px; width:400px; height:400px; margin:0 auto; display: flex; justify-content:center; align-items: center;">
                  <img style="height:300px; width:300px;display:none; object-fit: cover;" id="second-image" />
                </div>

                <br>

                <input type="file" name="user_image" class="addinput" id="addinput" accept="image/*"
                  onchange="previewImage2(event)" />

                <div class="profilelabel-div" style="width:405px; margin:0 auto; display:flex; justify-content:center;">
                  <label style="width:200px; height:10px" class="profilelabel" for="addinput">Choose
                    Image</label>
                </div>
                <br>
                <div style="margin-left:30px; display: flex; flex-direction: row;">
                  <div style="display: flex; justify-content: start;">
                    <textarea name="caption" class="form-control" id="caption" row="2" placeholder="caption"
                      style="width:330px; margin:0 auto; background-color: transparent; border: 2px solid lightpink; color:lightpink;"></textarea>
                  </div>
                  <button class="upload-profile" type="submit" style="margin:0 auto;margin-left:10px">Upload</button>
                </div>
              </form>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>
<!-- </div> -->
</div>
<script src="../dist/choreographer.min.js"></script>

<script>
  const previewImage = function (event) {
    const preview = document.getElementById('your-image');
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block"
  }

  const previewImage2 = function (event) {
    const preview = document.getElementById('second-image');
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block"
  }

  const Choreographer = require('choreographer-js')
  let choreographer = new Choreographer({
    animations: [
      {
        range: [-1, 1000],
        selector: '#box',
        type: 'scale',
        style: 'opacity',
        from: 0,
        to: 1
      }
    ]
  })

  window.addEventListener('scroll', () => {
    choreographer.runAnimationsAt(window.pageYOffset)
  })
</script>

<style>
  p {
    position: fixed;
    top: 100px;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    font-family: 'Arial', sans-serif;
    color: white;
    text-align: center;
    width: 100%;
    z-index: 1;
  }

  #box {
    margin: 0 0;
    width: 100%;
    height: 500vh;
    background: black;
    opacity: 0.2;
  }
</style>

{%endblock%}
</div>

instagram_web/blueprints/users/templates/users/request_page.html
{%for fan in fans%}
    <p>{{fan.name}}</p>
    <img src="http://nextagramtao.s3.amazonaws.com/{{fan.   profile_picture}}" style="width: 250px ; height: 200px;" class="mt-2">
    <form action="{{ url_for('users.follow_accept', id=fan.id)}}" method="POST" >
        <input type='hidden' name="csrf_token" value="{{ csrf_token()}}"/>
        <button type="submit" class="btn btn-primary"> Accept</button>
    </form>
    <form action="{{ url_for('users.follow_reject', id=fan.id)}}" method="POST" >
        <input type='hidden' name="csrf_token" value="{{ csrf_token()}}"/>
        <button type="submit" class="btn btn-primary"> Reject</button>
    </form>
    

{%endfor%}

instagram_web/blueprints/users/templates/users/sign_in.html
{% extends "_layout.html" %}

{% block title %}
Sign In
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<form action='{{url_for("users.signed_in")}}' method='POST'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="form-group">
        <label for="exampleInputU">Username</label>
        <input name='username' type="text" class="form-control" id="exampleInputU">
    </div>
    <div class="form-group">
        <label for="passInput">Password</label>
        <input name='password' type="password" class="form-control" id="passInput">
        <div id='passReply'>

        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

instagram_web/blueprints/users/templates/users/uploadprofile.html
{% extends "_layout.html" %}

{% block content %}

{% if errors %}
{% for error in errors %}
    <div class="alert alert-danger">
{{ error }}
</div>
{% endfor %}
{% endif %}

    <h1>Upload Your Files Bro</h1>

    <form action="{{ url_for('users.upload', id=current_user.id) }}" method="POST" enctype="multipart/form-data" >
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="user_file">Upload Your File</label>
        <br></br>
        <input type="file" name="user_file">
        <br></br>
        <button type="submit">Upload</button>

    </form>
{% endblock %}

instagram_web/blueprints/users/templates/users/userProfile.html
{% extends "_layout.html" %} {%block content%}

<h2 class="d-flex justify-content-center mx-auto" >
  User Profile
</h2>

<h3 class="d-flex justify-content-center mx-auto">{{user_id.name}}</h3>
<div class="justify-content-center mx-auto">
  {% if user_id.profile_image %}

  <img class="d-flex w-25 overflow-hidden justify-content-center mx-auto rounded-circle" src="{{user_id.profile_image_url}}" alt="">

  {%else%}

  <img class="d-flex justify-content-center mx-auto rounded-circle" src="{{url_for('static',filename='images/placeholder.png')}}" alt="placeholder">

  {% endif %}

{%if current_user.id == user.id %}
<div class="d-flex justify-content-center mt-3">
  {%if not user.private_profile == True %}
  <form method="post" action="{{url_for('users.private')}}">
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
    
    <button class="btn btn-outline-primary border-0 font-weight-bold" type="button submit">
      Private?
    </button>
    
  </form>
</div>
{% else %}

<form method="post" action="{{url_for('users.unprivate')}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />

  <button type="button submit">
    UnPrivate?
  </button>

</form>
</div>

{%endif%}

{%else%}
<div></div>
{%endif%}


<div class="d-flex justify-content-center mt-3 mx-auto">
  {% if not current_user.is_following(user) %}
  <form action="{{url_for('follows.create', idol_id=user.id)}}" method="post">

    <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
    <button class="mx-auto btn border-0 font-weight-bold btn-outline-primary"> Follow </button>
    
  </form>
{%else%}
  <form action="{{url_for('follows.delete', idol_id=user.id)}}" method="post">
  
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
    <button class="mx-auto btn border-0 font-weight-bold btn-outline-primary"> Unfollow </button>
  
  </form>
{%endif%}
</div>

<div class="d-flex flex-row text-center justify-content-center px-0 mx-auto d-flex">
  <div class="d-flex justify-content-center text-center col-2 ">  Followers: {{users.fans | length }} </div>

  <div class=" d-flex justify-content-center text-center col-2 ">  
    Following: {{users.idols | length }}
  </div>
</div>




<button type="button" class="border-0 font-weight-bold btn btn-outline-dark d-flex justify-content-center mx-auto my-2" data-toggle="modal"
  data-target="#uploadImage">
  Change Profile Picture
</button>
<div class="modal fade" id="uploadImage" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">
          Upload Profile Image
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{{url_for('users.upload', id=current_user.id)}}" enctype="multipart/form-data">
          <div class="form-group">
            
        
            <input id="image-form" type="hidden" name="csrf_token" value="{{csrf_token()}}" />
            <input name="profile_image" type="file" id="prof-img"
              >

          

          </div>
      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
      <button class="btn btn-primary" type="submit, button">
        Upload Image
      </button>
      </div>
      </form>
    </div>
  </div>
</div>




<button type="button" class="border-0 font-weight-bold btn btn-outline-dark d-flex justify-content-center mx-auto"  data-toggle="modal" data-target="#editProfile">
  Edit Profile
</button>
<div class="modal fade" id="editProfile" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">
          Update Profile Details
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{{url_for('users.user_profile_update', id=user_id)}}">
          <div class="form-group">
            <label for="username" class="col-form-label">New Username</label>
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
            <input name="NewUser" type="text" class="form-control" id="user-name" />
          </div>
          <div class="form-group">
            <label for="email" class="col-form-label">New Email</label>
            <input type="hidden" name="csrf_token" value="{{csrf_token()}}" />
            <input name="NewEmail" type="text" class="form-control" id="pass-word" />
          </div>
      </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <button type="button, submit" class="btn btn-primary">Save</button>
      </div>
      </form>
    </div>
  </div>
</div>

<hr>

<div class="overflow-hidden container">
<h3>Photo Album</h3>
</div>
<div class="overflow-hidden col-lg-10 d-flex flex-wrap justify-content-center container">
{% for i in user_id.images %}
<img class="col-3 overflow-hidden rounded d-block justify-content-center w-25 mx-3 my-3"  id="current_user.id" src="{{i.image_url}}">

{%endfor%}

</div>






{% endblock %}

instagram_web/blueprints/users/templates/users/userpage.html
{% extends "_layout.html" %}
{% block title %}Page Not Found{% endblock %}
{% block content %}
<div style="margin:10px">
  <h1>Hi {{current_user.username}}</h1>
  <h1>Your login details are:</h1>
  <form method="POST" action="{{url_for('users.update', id=current_user.id)}}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div style="margin:10px">
      <h6>Username</h6>
      <input style="border:deeppink 2px solid" class="form-control mr-sm-2" type="text"
        value="{{current_user.username}}" name="username">
      <button style="margin-top:5px" type="submit" class="btn btn-danger">Update</button>
    </div>
    <div style="margin:10px">
      <h6>Email</h6>
      <input style="border:deeppink 2px solid" class="form-control mr-sm-2" type="text" value={{current_user.email}}
        name="email">
      <button style="margin-top:5px" type="submit" class="btn btn-danger">Update</button>
    </div>
    <div style="margin:10px">
      <h6>Password</h6>
      <input style="border:deeppink 2px solid" class="form-control mr-sm-2" type="password" placeholder="password"
        name="password">
      <button style="margin-top:5px" type="submit" class="btn btn-danger">Update</button>
    </div>
  </form>
</div>

{% endblock %}