instagram_web/blueprints/monopoly/views.py
from flask import Blueprint, render_template, request, flash,  redirect, url_for
from flask_login import current_user, login_user, login_required
from models.user import User
from models.properties import Property
from models.activity_log import ActivityLog
from werkzeug.utils import secure_filename
from config import S3_BUCKET, S3_LOCATION
from helpers import upload_file_to_s3


monopoly_blueprint = Blueprint(
    'monopoly', __name__, template_folder='templates')


def activity_create(txt):
    new_activity = ActivityLog(text=txt)
    new_activity.save()
    activities = ActivityLog.select()
    if len(activities) > 8:
        new_activities = ActivityLog.select().order_by(
            ActivityLog.created_at.desc()).limit(8)
        old_activities = ActivityLog.select().where(
            ActivityLog.id.not_in([activity.id for activity in new_activities]))
        for old_act in old_activities:
            old_act.delete_instance()


def jail_free():
    current_user.jailed = -1
    current_user.doubles = 0
    current_user.save()


@monopoly_blueprint.route('/')
def index():
    if current_user.is_authenticated:
        users = User.select().where((User.monopoly > 0) & (User.username != 'Banker'))
        user_positions = []
        locations = ['Go', 'Old Kent Road', 'Community Chest', 'Whitechapel Road', 'Income Tax', "King's Cross Station", 'The Angel Islington', 'Chance', 'Euston Road', 'Pentonville Road', 'Jail', 'Pall Mall', 'Electric Company', 'Whitehall', 'Northumberland Ave.', 'Marylebone Station', 'Bow Street', 'Community Chest 2', 'Marlborough Street',
                     'Vine Street', 'Free Parking', 'Strand', 'Chance 2', 'Fleet Street', 'Trafalgar Square', 'Fenchurch St. Station', 'Leicester Square', 'Coventry Street', 'Water Works', 'Piccadilly', 'Go to Jail!', 'Regent Street', 'Oxford Street', 'Community Chest 3', 'Bond Street', 'Liverpool St. Station', 'Chance 3', 'Park Lane', 'Supertax', 'Mayfair']

        for user in users:
            user_positions.append(
                f'{user.username} @ {locations[user.position]} | with ${user.money}')

        current_property = Property.get_or_none(
            Property.name == locations[current_user.position])
        # if location:

        activities = ActivityLog.select().order_by(ActivityLog.created_at.desc())
        properties = Property.select()
        return render_template('monopoly/index1.html', user_positions=user_positions, properties=properties, activities=activities, users=users, current_property=current_property)

    else:
        flash('login is required', 'danger')
        return redirect(request.referrer)


@monopoly_blueprint.route('/create')
def create():
    user = User.get_or_none(User.id == current_user.id)
    if user.monopoly > 0:
        user.monopoly = 0
    else:
        user.monopoly = 1

    if user.save():
        flash('updated successfully', 'success')

    else:
        flash('failwhale', 'danger')

    return redirect(request.referrer)


@monopoly_blueprint.route('/roll', methods=['POST'])
def roll():

    roll_0 = request.form.get('roll-0')
    roll_1 = request.form.get('roll-1')
    jail_roll = int(request.form.get('jr-input'))
    roll_sum = int(roll_0) + int(roll_1)
    text = f'{current_user.username} rolled {roll_0} & {roll_1}.'
    # executes if this is a roll from jail.
    if jail_roll > 0:
        if roll_0 == roll_1:
            jail_free()
            activity_create(f'{text} Thus escaping jail.')
        elif current_user.jailed == 2:
            current_user.money -= 50
            jail_free()
            activity_create(
                f'{text} And got out of jail by paying $50')
        else:
            current_user.jailed += 1
            activity_create(
                f'{text} Thus failing to get out of jail.')
            current_user.save()
            return redirect(request.referrer)
    else:
        activity_create(text)
        if roll_0 == roll_1:
            current_user.doubles += 1
        else:
            current_user.doubles = 0

    current_user.position += roll_sum
    # current_user.position = 30
    current_user.save()

    if current_user.doubles == 3:
        current_user.position = 30

    current_user.save()

    if current_user.position > 39:
        current_user.position = current_user.position - 40
        current_user.money += 200

    if current_user.position == 30:
        current_user.position = 10
        current_user.jailed = 0
        current_user.doubles = 0

    if current_user.save():
        return redirect(request.referrer)
    else:
        flash('roll adding failed. Contact Shen.', 'danger')
        return redirect(request.referrer)


@monopoly_blueprint.route('/reset')
def reset():
    banker = User.get_or_none(User.username == 'Banker')
    users = User.select().where((User.monopoly > 0) & (User.username != 'Banker'))
    for user in users:
        user.jailed = -1
        user.position = 0
        user.money = 1500
        user.doubles = 0
        user.save()

    properties = Property.select()
    for prop in properties:
        prop.houses = 0
        prop.mortgaged = False
        prop.user_id = banker.id
        prop.save()

    banker.money = 1000000
    banker.save()
    deletion = ActivityLog.delete().where(ActivityLog.text != '')
    deletion.execute()
    return redirect(request.referrer)


@monopoly_blueprint.route('/jail-pay')
def jail_pay():
    if current_user.is_authenticated:
        current_user.money -= 50
        jail_free()
        if not current_user.save():
            flash('payment could not be done for some reason.', 'danger')
        else:
            activity_create(
                f'{current_user.username} payed $50 to get out of jail.')
    else:
        flash('need to be signed in to perform this action!', 'warning')

    return redirect(request.referrer)


@monopoly_blueprint.route('/pay', methods=['POST'])
def pay():
    if current_user.is_authenticated:
        recipient_username = request.form.get('recipient')
        amount = int(request.form.get('amount'))

        recipient = User.get_or_none(User.username == recipient_username)

        if amount > current_user.money:
            flash('sorry, but you too broke for that shit. lmao', 'warning')
            return redirect(request.referrer)

        current_user.money -= amount
        recipient.money += amount

        if current_user.save() and recipient.save():
            activity_create(
                f'{current_user.username} payed ${amount} to {recipient_username}')
            return redirect(request.referrer)


@monopoly_blueprint.route("/house", methods=['POST'])
def buy_house():
    return


@monopoly_blueprint.route('/new-property')
def new_property():
    if current_user.username == 'Banker':
        return render_template('monopoly/new-property.html')
    else:
        flash('sorry, but you do not have access to that feature!', 'danger')
        return redirect(url_for('monopoly.index'))


@monopoly_blueprint.route('/create-property', methods=['POST'])
def create_property():
    if current_user.username == 'Banker':
        name = request.form.get('name')
        house_price = request.form.get('house-price')
        category = request.form.get('category')
        if house_price == '':
            house_price = 0

        if "image-file" not in request.files:
            flash("No file was chosen! :O", 'warning')
            return redirect(request.referrer)
        file = request.files.get('image-file')
        file_name = secure_filename(file.filename)
        img_upload_err = str(upload_file_to_s3(file, S3_BUCKET))
        new_prop = Property(name=name, user_id=current_user.id,
                            house_price=house_price, category=category, image=file_name)
        if new_prop.save():
            flash('new property was saved', 'success')
            return redirect(url_for('monopoly.new_property'))
        else:
            flash(f'failed, {img_upload_err}', 'danger')
            return redirect(request.referrer)

instagram_web/blueprints/monopoly/templates/monopoly/WIP.html
WIP

<!-- house modal -->
<div class="modal fade" id="houseModal" tabindex="-1" role="dialog" aria-labelledby="houseModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="houseModalLabel">House/Hotel buying</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Your Money: ${{current_user.money}}
                <form id='pay-form' action="{{url_for('monopoly.buy_house')}}" method="post">
                    <input type="hidden" name="csrf_token" value='{{csrf_token()}}'>
                    <br>
                    <!-- Property selector -->
                    <input type="hidden" name="property" id="house-prop" value="">
                    <div class="form-group">
                        <label for="formControlSelect1">Select property!</label>
                        <select class="form-control" id="formControlSelect1">
                            <option value=""></option>
                            {% for property in current_user.properties %}
                            <option>{{property}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <br>
                    <input type="hidden" name="payer" value={{current_user.username}}>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" id='confirm-btn' class="btn btn-primary" disabled>Confirm</button>
            </div>
        </div>
    </div>
</div>

instagram_web/blueprints/monopoly/templates/monopoly/new-property.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet">

    {% assets "home_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    {% assets "home_js" %}
    <script src="https://kit.fontawesome.com/1816c993a6.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <title>New Property!</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class=flashes>
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <form action="{{url_for('monopoly.create_property')}}" method='POST' enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <label for="name-input">Property Name:</label>
        <input type="text" name="name" id='name-input'>
        <label for="house-price-input">Price of a House(if applicable):</label>
        <input type="text" name='house-price' id='house-price-input'>
        <label for="category-input">Category(colour, utility, station)</label>
        <input type="text" name='category' id='category-input'>
        <hr>
        <input type="file" name="image-file" id="image-file">
        <button type="submit">Submit</button>
    </form>
    <script>
        $(document).ready(() => {
            $('#image-file').change((e) => {
                console.log(e.target.value)
            })
        })
    </script>
</body>

</html>

instagram_web/blueprints/monopoly/templates/monopoly/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">
    <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap" rel="stylesheet">

    {% assets "home_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    {% assets "home_js" %}
    <script src="https://kit.fontawesome.com/1816c993a6.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <title>Mon Signup</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class=flashes>
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <form action='{{url_for("users.create")}}' method='POST'>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <div class="form-group">
            <label for="exampleInputU">Username</label>
            <input name='username' type="text" class="form-control" id="exampleInputU">
        </div>
        <div class="form-group">
            <label for="passInput">Password</label>
            <input name='password' type="password" class="form-control" id="passInput">
            <div id='passReply'></div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>

</html>