instagram_web/blueprints/cards/views.py
from flask import request, redirect, url_for, render_template, flash, Blueprint
from models.cards import Card
import json
from flask_socketio import send, emit
from app import socketio
from flask_login import current_user
from models.user import User
from werkzeug.utils import secure_filename
from helpers import upload_file_to_s3
from config import S3_BUCKET

cards_blueprint = Blueprint('cards', __name__, template_folder='templates')


@cards_blueprint.route('/new')
def new():
    return render_template('cards/new.html')


@cards_blueprint.route('/create', methods=['POST'])
def create():
    description = request.form.get('description')
    category = request.form.get('category')
    if 'image-file' not in request.files:
        flash('no file was chosen!', 'warning')
        return redirect(request.referrer)
    file = request.files.get('image-file')
    file_name = secure_filename(file.filename)
    img_upload_err = str(upload_file_to_s3(file, S3_BUCKET))
    new_card = Card(description=description,
                    category=category, image=file_name)

    if new_card.save():
        flash('new card was saved', 'success')
    else:
        flash(f'saving failed, {img_upload_err}', 'danger')

    return redirect(request.referrer)


@cards_blueprint.route('/')
def index():
    cards = Card.select()
    return render_template('cards/index.html', cards=cards)

instagram_web/blueprints/cards/templates/cards/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% for card in cards %}
    <p>
        <img src="{{card.image_url}}" width='300px' alt="">
        {{card.category}}
    </p>
    {% endfor %}
</body>

</html>

instagram_web/blueprints/cards/templates/cards/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% assets "home_css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
    {% assets "home_js" %}
    <script src="https://kit.fontawesome.com/1816c993a6.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    <title>New Property!</title>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class=flashes>
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <form action="{{url_for('cards.create')}}" method='POST' enctype="multipart/form-data">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
        <label for="description-input">Description:</label>
        <input type="text" name="description" id='description-input'>
        <label for="category-input">Category(chance or community)</label>
        <input type="text" name='category' id='category-input'>
        <hr>
        <input type="file" name="image-file" id="image-file">
        <img src="" width='300px' id='mon-preview' alt="">
        <button type="submit">Submit</button>
    </form>
    <script>
        $(document).ready(() => {
            $('#image-file').change((e) => {
                $('#mon-preview').attr('src', URL.createObjectURL(e.target.files[0]))
                console.log(e.target)
            })
        })
    </script>
</body>

</html>